### ISSUE TITLE
Provide a snap package

### ISSUE THREAD

**Issue by soullivaneuh** [junegunn/fzf#1497]
Snap is a package manager aim to work on multiple OS.

Apparently, anybody can create a snap.

Maybe you can provide your own official snap?

Two already exist: https://snapcraft.io/search?category=&q=fzf

But the first one is not up to date from a time and the second one does not seem to work after the installation.

What do you think?

Regards

**Comment by tetienne** [comment]
Will be a great and nice alternative to Linuxbrew!

**Comment by pckilgore** [comment]
Checkout the branch above for a start at this, but for those who want to be able to install a fully-functional v0.20 right now, you should be able to:
`sudo snap install --edge fzf-unofficial-18-04 --devmode`

To use it you need to invoke `fzf-unofficial-18-04.fzf` so you'll probably want to setup an alias :upside_down_face: 

Obviously, you should not be installing random snaps will full permissions like this built by internet strangers, so make your own decision whether me and this package is trustworthy.

But for reference, here's the basic recipe I used for this edge package:

```
name: fzf-unofficial-18-04
version: git
summary: A general-purpose command-line fuzzy finder.
description: |
  An unofficial snap build of fzf for Ubuntu 18.04.  The fzf package provides an
  interactive Unix filter for command-line that can be used with any list;
  files, command history, processes, hostnames, bookmarks, git commits, etc.
base: core18
grade: stable
confinement: devmode

parts:
  fzf:
    plugin: go
    go-importpath: github.com/junegunn/fzf
    source: ..
    source-type: git

apps:
  fzf:
    command: bin/fzf
```

Note this assumes that your `snapcraft.yml` file sits in the /snap directory of the master branch if you're paranoid (you should be) and want to build and install it yourself (you should, use --dangerous).
