### ISSUE TITLE
[Question] Install and configure using ansible

### ISSUE THREAD

**Issue by lonix1** [junegunn/fzf#1829]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] bash
    - [x] zsh
    
## Problem / Steps to reproduce

Does anyone have an ansible task to share for installing and configuring fzf?

I found that the apt package (for debian) does not work well, so it's not straightforward. So when installing fzf I need to use the git installation approach.

Also, fzf automatically modifies bashrx/zshrc and when using ansible this needs to be more carefully (or manually) controlled.

Any sample tasks appreciated.

**Comment by dovry** [comment]
the [Git](https://docs.ansible.com/ansible/latest/modules/git_module.html) task and either [Blockinfile](https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html) or [Lineinfile](https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html) would probably work

**Comment by lonix1** [comment]
@dovry Maybe... that was what I initially thought. But the installer does it's own thing, that's the problem.

I'm hoping someone has a tested task to share. It would have to hijack the fzf automatic installation process, and substitute it with something manual.

**Comment by dovry** [comment]
Well, you have [Expect](https://docs.ansible.com/ansible/latest/modules/expect_module.html) which can answer the questions for you

```shell
Do you want to update your shell configuration files? ([y]/n) y

Update /home/dovry/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #121 

Update /home/dovry/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    + Added
```

so if you don't want fzf to modify the .*rc files you can use expect to say no, then add the lines with line/blockinfile to add `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh`

**Comment by junegunn** [comment]
```
$ ./install --help
usage: ./install [OPTIONS]

    --help               Show this message
    --bin                Download fzf binary only; Do not generate ~/.fzf.{bash,zsh}
    --all                Download fzf binary and update configuration files
                         to enable key bindings and fuzzy completion
    --xdg                Generate files under $XDG_CONFIG_HOME/fzf
    --[no-]key-bindings  Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)
    --[no-]completion    Enable/disable fuzzy completion (bash & zsh)
    --[no-]update-rc     Whether or not to update shell configuration files

    --no-bash            Do not set up bash configuration
    --no-zsh             Do not set up zsh configuration
    --no-fish            Do not set up fish configuration

    --32                 Download 32-bit binary
    --64                 Download 64-bit binary
```

**Comment by dovry** [comment]
lol yeah sometimes it's hard to RTFM, anyway

```yaml
---
- name: make sure git is installed
  package:
    name: git
    state: present

- name: fetch fzf from github
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: /tmp/fzf/
    version: HEAD # latest

- name: Run install script
  script: /tmp/fzf/install --no-key-bindings --no-completion --no-update-rc
```

Confirmed that this is working in my ansible container
![image](https://user-images.githubusercontent.com/15201298/72894010-abdc3180-3d1a-11ea-9841-c8d061b71e74.png)

**Comment by lonix1** [comment]
@dovry @junegunn You guys rock... thanks! 😃 

@junegunn I assume fzf only adds config for `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` for bash, zsh and fish - that's it. If I'm adding that manually, I don't need to do anything else?

**Comment by dovry** [comment]
@lonix1 try to run the script manually and take a look at the output to see what is going on.

**Comment by fffx** [comment]
I use apt install fzf, here is my ansible update keybinding task:
```
- shell: 'dpkg -L fzf | grep -e "key-bindings\.zsh$"'
  register: zsh_binding
- name: Fzf binding 
  lineinfile:
    path: ~/.zshrc
    line: ". {{zsh_binding.stdout}}"
    regex: 'fzf/.*key-bindings\.zsh$'
    state: present
```

**Comment by carpii** [comment]
The above solutions weren't suitable for me, so I ended up with this. The /usr/share paths are applicable to Ubuntu server, gleaned from `dpkg -L fzf`

````
- name: Install fzf
  ansible.builtin.apt:
    name: fzf
    state: present
    force_apt_get: true

- name: Install fzf completions 
  ansible.builtin.lineinfile:
    path: "/home/{{ remote_user }}/.bashrc"
    line: "[ -f /usr/share/bash-completion/completions/fzf ] && source /usr/share/bash-completion/completions/fzf"
    create: yes

- name: Install fzf keybindings 
  ansible.builtin.lineinfile:
    path: "/home/{{ remote_user }}/.bashrc"
    line: "[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash"
    create: yes
````
