### ISSUE TITLE
Height of preview window depends on length of fzf items list

### ISSUE THREAD

**Issue by ret2src** [junegunn/fzf#4110]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (fc693080)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

For fast file selection, I've configured `fzf` to show a preview window.

This works as intended for directories with many files:

![Many files with large preview window](https://github.com/user-attachments/assets/cc1883e0-93e1-4520-99f1-e5ffcc29a8ce)

However, if a directory has only a few files, the preview is too short to add any value:

![Few files with small preview window](https://github.com/user-attachments/assets/ea6ceffd-bb4f-4280-ad10-6f3dc9b86857)

Unfortunately, I couldn't find a solution yet. I think there should be an option or environment variable to force the `fzf` preview window to use as much vertical space as possible to solve this issue.

**Comment by junegunn** [comment]
Have you tried using `--min-height` option?

**Comment by ret2src** [comment]
I have the following default options in my zsh environment (just added `--min-height=100`, but it doesn't seem to have any effect):

``` bash
export FZF_DEFAULT_OPTS='--preview-window=right,60%
                         --height=100%
                         --min-height=100
                         --info=right
                         --multi
                         --extended
                         --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all,?:toggle-preview,ctrl-b:preview-page-up,ctrl-f:preview-page-down,shift-up:preview-up,shift-down:preview-down
                         --prompt="  "
                         --pointer="󰁕"
                         --marker=""
                         --color=dark'
```

My `.zshrc` contains the following:

``` bash
[...]
# Improve `fzf` file previews (the `fzf-dynamic-preview` function is defined in `.zshenv`).
zstyle ':fzf-tab:complete:*:*' fzf-preview 'fzf-dynamic-preview $realpath'
[...]
# Load `fzf` zsh integration, which provides fzf-powered history search and file completion (requires fzf >= 0.52.1).
eval "$(fzf --zsh)"
[...]
```

I use the following zsh plugin through [sheldon](https://github.com/rossmacarthur/sheldon):

```toml
# Description: Replaces zsh's default completion selection menu with fzf.
# Rationale: Greatly improves selection speed by utilizing the fuzzy-matching algorithm of `fzf`.
# Notes: Make sure that this plugin is loaded after other plugins that bind `^I`, i.e. place it near the bottom of your plugin list. However, also make sure that it's loaded before `zsh-autosuggestions` and `zsh-syntax-highlighting`.
# Source: https://github.com/Aloxaf/fzf-tab
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
```
