### ISSUE TITLE
Release files name pattern - scriptable

### ISSUE THREAD

**Issue by gomesar9** [junegunn/fzf#4146]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.57.0 (0476a65)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi all,

I'm automating some installations using Ansible, and many current tools are distributed via GitHub releases. I've noticed that some projects use version-agnostic file names for their release artifacts, which greatly simplifies the process of automating downloads.

This code snippet exemplifies an Ansible task where the download URL can be easily constructed due to stable file names:

```
    - name: Check latest if any installed
      ansible.builtin.shell: |
        set -o pipefail && curl -s -D- {{ gh_tool_repo }}/releases/latest |
        {{ gh_tool_version_regex }}

    - name: "Download  archive [{{ gh_tool_name }}]"
      ansible.builtin.get_url:
        url: "{{ gh_tool_repo }}/releases/latest/download/{{ gh_tool_download_file_name }}"
        dest: "{{ tmp_dir.path }}/gh_tool.tar.gz"
        mode: "0755"
```
When file names include the version, it adds complexity to automation scripts, as they need to dynamically determine the latest version before constructing the download URL. This typically involves request a tag into the input variable, and a replace logic.

I would appreciate it if you could evaluate adopting this approach.

Thank you for your time and consideration.

--EDIT:
I also wanted to mention another point related to automation. Having the fzf --version output match the tag format (including the "v" prefix, e.g., v0.50.1, instead of 0.50.1) would further simplify automation scripts that rely on comparing versions. This inconsistency currently requires additional string manipulation. Thank you.
